-- Benchmark harness for LibDeflateGuard, optionally against a reference
-- module. Run from the repository root: luajit tests/BenchTest.lua
--
-- Set LIBDEFLATEGUARD_BENCH_REFERENCE to the path of another module to
-- compare the two, path by path. It accepts either an upstream LibDeflate.lua
-- or an older LibDeflateGuard.lua, and adapts the call shape to whichever it
-- is. Unset, the harness benchmarks this module alone and prints absolute
-- numbers, which is all the saturation shapes need.
--
-- Six migration-relevant paths are compared, sized like real addon traffic,
-- plus the two saturation shapes that size a policy: a match bomb and an
-- import blob, each run at the "addon" and "generous" presets, each
-- saturating its own output cap.
--
-- Nothing here fails on a timing result, however bad. Timing on any machine
-- anyone has is noise at the percent level, and a threshold over noise is a
-- flaky test rather than a gate. The byte-identical cross-checks run before
-- any timing and are the only thing that can fail.
--
-- The point of this file is that a documentation table can be regenerated by
-- a stranger and come out the same. Every choice below that had a
-- faster-looking answer and a more reproducible one took the reproducible
-- one: the corpus comes from a private seeded generator rather than
-- math.random, the reported figure is a median of alternated rounds rather
-- than a best-of, and the spread is printed next to it so a reader can see
-- when a difference is smaller than the machine can measure.
--
-- Environment:
--   LIBDEFLATEGUARD_BENCH_SEED      corpus seed (default 1234)
--   LIBDEFLATEGUARD_BENCH_ROUNDS    alternated A/B rounds (default 21)
--   LIBDEFLATEGUARD_BENCH_REFERENCE path to a reference module
package.path = "?.lua;" .. (package.path or "")

local failures = 0
local checks_run = 0

local function Check(name, func)
  checks_run = checks_run + 1
  local ok, message = pcall(func)
  if ok then
    io.write("ok - ", name, "\n")
  else
    failures = failures + 1
    io.stderr:write("not ok - ", name, ": ", tostring(message), "\n")
  end
end

local Guard = require("LibDeflateGuard")

local reference_path = os.getenv("LIBDEFLATEGUARD_BENCH_REFERENCE")
local Reference
if reference_path and reference_path ~= "" then
  Reference = assert(dofile(reference_path),
                     "reference module did not return a table")
end

local seed = tonumber(os.getenv("LIBDEFLATEGUARD_BENCH_SEED") or "") or 1234
local rounds = tonumber(os.getenv("LIBDEFLATEGUARD_BENCH_ROUNDS") or "") or 21

-- The same generator FuzzTest uses, and the same rejection rule for a seed it
-- cannot represent identically everywhere. A published number must come from
-- a corpus that is byte for byte the same on every interpreter, so a seed
-- that means one thing under LuaJIT's doubles and another under 5.4's
-- integers is refused rather than quietly run.
if not (seed == math.floor(seed) and seed >= 0 and seed < 2147483647) then
  io.stderr:write("LIBDEFLATEGUARD_BENCH_SEED must be a whole number below ",
                  "2147483647, got ", tostring(seed), "\n")
  os.exit(1)
end
-- Three rounds is the floor for the decile band below to describe anything.
if not (rounds == math.floor(rounds) and rounds >= 3) then
  io.stderr:write("LIBDEFLATEGUARD_BENCH_ROUNDS must be a whole number of at ",
                  "least 3, got ", tostring(rounds), "\n")
  os.exit(1)
end

-- MINSTD, exactly as in tests/FuzzTest.lua: state = state * 16807 % (2^31-1).
-- It peaks near 2^45, which is exact in both the double and the 64-bit integer
-- arithmetic the supported interpreters use, so a seed means the same corpus
-- everywhere. AssertGeneratorIsPortable pins it rather than trusting that.
local rng_state = seed % 2147483647
if rng_state == 0 then rng_state = 1 end -- 0 is MINSTD's fixed point
local function Random(upper)
  rng_state = rng_state * 16807 % 2147483647
  -- math.floor keeps this an integer on 5.3+, where "/" yields a float.
  return math.floor(rng_state / 2147483647 * upper)
end

-- The same values FuzzTest checks, taken from Lua 5.1. A corpus that is not
-- identical everywhere makes every number below unpublishable, so this is
-- checked, not assumed.
local function AssertGeneratorIsPortable()
  local saved = rng_state
  rng_state = 1234
  local expected = {19, 635, 833, 1948, 869, 391, 106, 1438, 503, 822}
  for index = 1, #expected do
    local drawn = Random(2000)
    assert(drawn == expected[index],
           ("generator is not portable on %s: draw %d gave %s, expected %d"):format(
             _VERSION, index, tostring(drawn), expected[index]))
  end
  rng_state = saved
end

-- Checked before a single byte of corpus is drawn, because a generator that
-- disagrees with the one FuzzTest uses makes every corpus below a different
-- corpus from the one a reader would build.
Check("the corpus generator is identical on every interpreter",
      function() AssertGeneratorIsPortable() end)

local function RandomString(length, alphabet)
  local parts = {}
  for i = 1, length do
    if alphabet then
      local index = 1 + Random(#alphabet)
      parts[i] = alphabet:sub(index, index)
    else
      parts[i] = string.char(Random(256))
    end
  end
  return table.concat(parts)
end

-- Prose-shaped text drawn from a fixed vocabulary. This is the "compressible
-- text" corpus: it compresses about 3.5:1, which is what a chat message or a
-- serialised addon table does, rather than the 200:1 a run of one byte does.
local VOCABULARY = {}
for i = 1, 64 do
  VOCABULARY[i] = RandomString(2 + Random(9), "abcdefghijklmnopqrstuvwxyz")
end

local function Text(size)
  local parts, filled = {}, 0
  while filled < size do
    local word = VOCABULARY[1 + Random(#VOCABULARY)]
    parts[#parts + 1] = word
    parts[#parts + 1] = Random(8) == 0 and "\n" or " "
    filled = filled + #word + 1
  end
  return table.concat(parts):sub(1, size)
end

-- The import blob: a serialised addon table, which is a long run of one
-- record shape with a few fields varying. That is what makes a real import
-- both large and highly compressible, and it is the shape that reaches an
-- output cap from an input a policy would still admit.
local BLOB_KEYS = {
  "displayText", "actions", "triggers", "conditions", "load", "animation",
  "regionType", "anchorPoint", "xOffset", "yOffset", "fontSize", "color"
}
local BLOB_REGIONS = {"aura_env_display", "aura_env_progress", "aura_env_icon"}

local function Blob(size)
  local parts, filled, index = {}, 0, 0
  while filled < size do
    index = index + 1
    local record = ([[
      ["%s"] = {
        ["id"] = %d,
        ["value"] = %d,
        ["enabled"] = %s,
        ["region"] = "%s",
      },
]]):format(BLOB_KEYS[1 + Random(#BLOB_KEYS)], index % 100, Random(100),
           Random(2) == 0 and "true" or "false",
           BLOB_REGIONS[1 + Random(#BLOB_REGIONS)])
    parts[#parts + 1] = record
    filled = filled + #record
  end
  return table.concat(parts):sub(1, size)
end

-- The preset numbers, written out. LIMIT_PRESETS arrived in v1.1.0, and both
-- CONTRIBUTING.md and this file's own header promise that an older
-- LibDeflateGuard.lua works as a reference. v1.0.0 and v1.0.1 ship a single
-- set of default limits -- the ones that later became "generous" -- and no
-- preset table at all, but they still take a limits table on every
-- decompress, so handing them these numbers enforces exactly what a modern
-- module enforces under the same preset name. Without this, BindApi indexed a
-- nil LIMIT_PRESETS and the harness died with a traceback on the very
-- references it advertises.
local PRESET_LIMITS = {
  addon = {
    max_input_bytes = 64 * 1024,
    max_output_bytes = 512 * 1024,
    max_blocks = 256,
    max_symbols = 750000,
    max_work_units = 1500000
  },
  generous = {
    max_input_bytes = 1024 * 1024,
    max_output_bytes = 8 * 1024 * 1024,
    max_blocks = 4096,
    max_symbols = 10000000,
    max_work_units = 25000000
  }
}

-- A literal copy of a number this module also ships is a number that can
-- drift. Checked rather than trusted, before anything is measured under it.
Check("the literal preset numbers match this module's LIMIT_PRESETS", function()
  for preset_name, literal in pairs(PRESET_LIMITS) do
    local shipped = Guard.LIMIT_PRESETS[preset_name]
    assert(type(shipped) == "table",
           ("this module has no %s preset"):format(preset_name))
    for key, value in pairs(literal) do
      assert(shipped[key] == value,
             ("%s.%s: this file says %s, the module says %s"):format(
               preset_name, key, tostring(value), tostring(shipped[key])))
    end
  end
end)

-- The reference may be upstream LibDeflate or an older LibDeflateGuard, and
-- the two do not take the same arguments: upstream's DecompressDeflate takes
-- no policy and its codec decoders take no cap. Dispatch on the module rather
-- than passing a value upstream will read as something else. Upstream ignores
-- a trailing argument today, but a value landing in a slot that a later
-- version gives a meaning to is precisely the v1.1.2 fault, so the bound
-- calls below never pass one they are not sure of.
--
-- Everything is bound once, before any timing, so the dispatch is not paid
-- per call and cannot show up as a difference between the two modules.
local function BindApi(module, preset_name)
  local api = {}
  if module._NAME == "LibDeflateGuard" then
    -- The module's own preset when it has one, the literal numbers when it is
    -- old enough not to. Both are the same values; see PRESET_LIMITS above.
    local presets = module.LIMIT_PRESETS
    local policy = (type(presets) == "table" and presets[preset_name]) or
                     PRESET_LIMITS[preset_name]
    assert(policy, ("module %s has no %s preset and this harness has no " ..
             "literal fallback for that name"):format(tostring(module._VERSION),
                                                      tostring(preset_name)))
    -- The codec decoders gained their input cap in v1.1.0, alongside
    -- LIMIT_PRESETS and DEFAULT_CODEC_LIMITS. On an older module that
    -- parameter does not exist, and putting a value into a slot the callee
    -- has no meaning for is exactly the v1.1.2 fault, so it is not passed.
    local takes_codec_cap = type(module.DEFAULT_CODEC_LIMITS) == "table"
    -- The same ratios the module derives its own codec caps with: the print
    -- codec emits 0.75 bytes per input byte, the channel codecs never grow
    -- their input. WithPolicy is not used here because a reference old enough
    -- to predate it must still be measurable.
    local print_cap = math.floor(policy.max_input_bytes * 4 / 3)
    local channel_cap = policy.max_input_bytes
    api.label = ("%s %s, %s policy%s"):format(module._NAME,
                                              tostring(module._VERSION),
                                              preset_name, takes_codec_cap and
                                                "" or
                                                ", codec decoders take no cap")
    function api.DecompressDeflate(str)
      return module:DecompressDeflate(str, policy)
    end
    if takes_codec_cap then
      function api.DecodeForPrint(str)
        return module:DecodeForPrint(str, print_cap)
      end
      function api.DecodeForWoWAddonChannel(str)
        return module:DecodeForWoWAddonChannel(str, channel_cap)
      end
      function api.DecodeForWoWChatChannel(str)
        return module:DecodeForWoWChatChannel(str, channel_cap)
      end
    else
      function api.DecodeForPrint(str) return module:DecodeForPrint(str) end
      function api.DecodeForWoWAddonChannel(str)
        return module:DecodeForWoWAddonChannel(str)
      end
      function api.DecodeForWoWChatChannel(str)
        return module:DecodeForWoWChatChannel(str)
      end
    end
  else
    api.label = ("LibDeflate %s"):format(tostring(module._VERSION))
    function api.DecompressDeflate(str) return module:DecompressDeflate(str) end
    function api.DecodeForPrint(str) return module:DecodeForPrint(str) end
    function api.DecodeForWoWAddonChannel(str)
      return module:DecodeForWoWAddonChannel(str)
    end
    function api.DecodeForWoWChatChannel(str)
      return module:DecodeForWoWChatChannel(str)
    end
  end
  return api
end

-- Corpora. Sizes are named here rather than buried in the shapes, because
-- every number this file prints is per call on exactly these bytes.
local TEXT_BYTES = 8192
local STORED_BYTES = 8192
local SMALL_BYTES = 256

local text_payload = Text(TEXT_BYTES)
local text_member = Guard:CompressDeflate(text_payload)
local stored_payload = RandomString(STORED_BYTES)
local stored_member = Guard:CompressDeflate(stored_payload, {level = 0})
local small_payload = Text(SMALL_BYTES)
local small_member = Guard:CompressDeflate(small_payload)

-- Real traffic is compress-then-encode, so every codec shape decodes an
-- encoded member rather than encoded prose.
local addon_encoded = Guard:EncodeForWoWAddonChannel(text_member)
local chat_encoded = Guard:EncodeForWoWChatChannel(text_member)
local print_encoded = Guard:EncodeForPrint(text_member)
local small_encoded = Guard:EncodeForWoWAddonChannel(small_member)

local migration_shapes = {
  {
    name = "DecompressDeflate, compressible text",
    input = text_member,
    expected = text_payload,
    Run = function(api, str) return api.DecompressDeflate(str) end
  }, {
    name = "DecompressDeflate, stored blocks",
    input = stored_member,
    expected = stored_payload,
    Run = function(api, str) return api.DecompressDeflate(str) end
  }, {
    name = "DecodeForWoWAddonChannel",
    input = addon_encoded,
    expected = text_member,
    Run = function(api, str) return api.DecodeForWoWAddonChannel(str) end
  }, {
    name = "DecodeForWoWChatChannel",
    input = chat_encoded,
    expected = text_member,
    Run = function(api, str) return api.DecodeForWoWChatChannel(str) end
  }, {
    name = "DecodeForPrint",
    input = print_encoded,
    expected = text_member,
    Run = function(api, str) return api.DecodeForPrint(str) end
  }, {
    -- The shape the World of Warcraft use case actually generates, and the
    -- one where fixed per-call overhead is visible rather than amortised.
    name = "Small message, decode then decompress",
    input = small_encoded,
    expected = small_payload,
    Run = function(api, str)
      local decoded = api.DecodeForWoWAddonChannel(str)
      if not decoded then return nil end
      return api.DecompressDeflate(decoded)
    end
  }
}

-- The saturation shapes. Each one is built to decode to exactly the preset's
-- max_output_bytes, so what is measured is the worst work the policy accepts
-- rather than whatever a convenient payload happened to cost. These need no
-- reference module: the question they answer is "how long does this policy
-- let a single call take", which is about this module alone.
local saturation_shapes = {}
for _, preset_name in ipairs({"addon", "generous"}) do
  local preset = Guard.LIMIT_PRESETS[preset_name]
  local api = BindApi(Guard, preset_name)
  local bomb_payload = string.rep("A", preset.max_output_bytes)
  local blob_payload = Blob(preset.max_output_bytes)
  local shapes = {
    {shape = "match bomb", member = Guard:CompressDeflate(bomb_payload)},
    {shape = "import blob", member = Guard:CompressDeflate(blob_payload)}
  }
  for _, entry in ipairs(shapes) do
    saturation_shapes[#saturation_shapes + 1] =
      {
        name = ("%s, %s"):format(preset_name, entry.shape),
        preset = preset_name,
        shape = entry.shape,
        api = api,
        input = entry.member,
        decoded_bytes = preset.max_output_bytes,
        Run = function(bound, str) return bound.DecompressDeflate(str) end
      }
  end
end

local guard_api = BindApi(Guard, "addon")
local reference_api = Reference and BindApi(Reference, "addon") or nil

-- Cross-checks. Byte-identical output on every shape, asserted before a
-- single timing round runs, because a benchmark of two functions that do not
-- agree measures nothing. This is the only part of the harness allowed to
-- fail.
--
-- Only the decoded bytes are compared, not the whole return tuple. The second
-- return value is deliberately not the same thing in the two modules: this
-- module answers a status, upstream answers the count of unprocessed bytes.
-- Comparing tuples is FuzzTest's job and it does it against a guard reference,
-- where the tuples are comparable.
for _, shape in ipairs(migration_shapes) do
  Check("cross-check: " .. shape.name, function()
    local mine = shape.Run(guard_api, shape.input)
    assert(mine == shape.expected,
           shape.name .. ": this module did not return the expected bytes")
    if reference_api then
      local theirs = shape.Run(reference_api, shape.input)
      assert(theirs ~= nil, shape.name .. ": the reference returned nil")
      assert(mine == theirs,
             ("%s: output differs, this module %d bytes, reference %d bytes"):format(
               shape.name, #mine, #theirs))
    end
  end)
end

for _, shape in ipairs(saturation_shapes) do
  Check("cross-check: " .. shape.name .. " saturates its output cap", function()
    local decoded = shape.Run(shape.api, shape.input)
    assert(decoded ~= nil,
           shape.name .. ": the shape must be accepted by its own preset")
    assert(#decoded == shape.decoded_bytes,
           ("%s: decoded %d bytes, the cap is %d"):format(shape.name, #decoded,
                                                          shape.decoded_bytes))
  end)
end

if failures > 0 then
  io.stderr:write(
    ("%d of %d cross-checks failed; refusing to time modules "):format(failures,
                                                                       checks_run),
    "that do not agree\n")
  os.exit(1)
end

-- Timing. os.clock is the only clock every supported interpreter has, and on
-- Windows it ticks at a millisecond, so a round has to be long enough that a
-- tick is a small part of it. Rounds are sized by calibration rather than by
-- a constant, so that the same file measures something on an interpreter ten
-- times faster or slower than the one it was written on.
local TARGET_ROUND_SECONDS = 0.1
local MAX_CALLS = 1000000

-- Holds the result of every timed call reachable, so that no interpreter can
-- conclude the call is dead and skip it. The value is meaningless and is
-- never printed.
local sink = 0

local function TimeCalls(shape, api, calls)
  -- Collected outside the timed region, so that one round does not pay for
  -- the garbage of the round before it.
  collectgarbage("collect")
  local input = shape.input
  local Run = shape.Run
  local start = os.clock()
  for _ = 1, calls do
    local result = Run(api, input)
    if result then sink = sink + #result end
  end
  return os.clock() - start
end

local function Calibrate(shape, api)
  local calls = 1
  while calls < MAX_CALLS do
    local elapsed = TimeCalls(shape, api, calls)
    if elapsed >= TARGET_ROUND_SECONDS then
      local scaled = math.floor(calls * TARGET_ROUND_SECONDS / elapsed + 0.5)
      return scaled < 1 and 1 or scaled
    end
    calls = calls * 2
  end
  return calls
end

local function Median(sorted)
  local count = #sorted
  if count % 2 == 1 then return sorted[(count + 1) / 2] end
  return (sorted[count / 2] + sorted[count / 2 + 1]) / 2
end

-- Nearest-rank decile. The spread this harness reports is half the p10 to p90
-- band as a fraction of the median. A plain max minus min would be one
-- outlier wide -- a single collection or a scheduling hiccup sets it -- and
-- would declare every result inside the measurement floor. The deciles drop
-- the extremes at both ends and still describe a genuinely wide sample.
local function Decile(sorted, fraction)
  local rank = math.floor(#sorted * fraction + 0.5)
  if rank < 1 then rank = 1 end
  if rank > #sorted then rank = #sorted end
  return sorted[rank]
end

local function Summarize(samples)
  local sorted = {}
  for i = 1, #samples do sorted[i] = samples[i] end
  table.sort(sorted)
  local median = Median(sorted)
  local low, high = Decile(sorted, 0.1), Decile(sorted, 0.9)
  return {
    median = median,
    spread = median > 0 and (high - low) / 2 / median or 0
  }
end

-- Allocated bytes per call: one call with the collector stopped, so the
-- figure counts everything the call allocated, including what it threw away
-- immediately. That is deliberately not peak heap, which cannot be sampled
-- from inside Lua without instrumenting the module. Allocation is the
-- reproducible one of the two, so it is the one reported.
--
-- Medianed over several samples, for the same reason every timing figure in
-- this file is. collectgarbage("count") is a kilobyte counter read either
-- side of the call, so it quantises, and the collector's own bookkeeping
-- lands inside the window: a single sample moved by up to a kilobyte between
-- runs on a 5.5 KB figure, which is enough to break the "identical to the
-- byte" reading the codec decoders in fact support. The median of a handful
-- of samples reproduces exactly.
local ALLOC_SAMPLES = 11

local function AllocOnce(shape, api)
  collectgarbage("collect")
  collectgarbage("collect")
  local before = collectgarbage("count")
  collectgarbage("stop")
  local result = shape.Run(api, shape.input)
  local after = collectgarbage("count")
  collectgarbage("restart")
  if result then sink = sink + #result end
  return (after - before) * 1024
end

local function AllocPerCall(shape, api)
  local samples = {}
  for index = 1, ALLOC_SAMPLES do samples[index] = AllocOnce(shape, api) end
  table.sort(samples)
  return Median(samples)
end

-- Measures one shape against one or two bound modules. The call count is the
-- larger of the two calibrations, so both modules always run the same number
-- of calls per round and a round is above the clock floor for whichever is
-- faster.
local function Measure(shape, apis)
  local calls = 1
  for _, api in ipairs(apis) do
    local calibrated = Calibrate(shape, api)
    if calibrated > calls then calls = calibrated end
  end
  local samples = {}
  for index = 1, #apis do samples[index] = {} end
  for round = 1, rounds do
    -- Alternated, and the order flips every round, so that neither module
    -- systematically runs first on a cold cache or last on the other's
    -- garbage. A best-of would be cheaper and is what this repository has
    -- already been burned by: item C read a branch 6.9% faster than a branch
    -- it cannot be faster than.
    local first, last, step = 1, #apis, 1
    if round % 2 == 0 then first, last, step = #apis, 1, -1 end
    for index = first, last, step do
      samples[index][round] = TimeCalls(shape, apis[index], calls) / calls
    end
  end
  local results = {calls = calls}
  for index = 1, #apis do
    results[index] = Summarize(samples[index])
    results[index].alloc = AllocPerCall(shape, apis[index])
  end
  -- The delta is the median of the per-round ratios, not the ratio of the two
  -- medians. Alternating the two modules inside one round is only worth doing
  -- if the pairing is then used: a round that ran slowly because something
  -- else on the machine wanted the CPU slowed both modules, and dividing
  -- within the round cancels that. The ratio's own spread is therefore a much
  -- tighter and more honest floor for the comparison than either module's
  -- absolute spread, which is dominated by whatever else the machine is doing.
  if #apis == 2 then
    local ratios = {}
    for round = 1, rounds do
      local divisor = samples[2][round]
      ratios[round] = divisor > 0 and samples[1][round] / divisor or 1
    end
    results.ratio = Summarize(ratios)
  end
  return results
end

local function FormatBytes(bytes)
  if bytes >= 1024 * 1024 then return ("%.1f MB"):format(bytes / 1024 / 1024) end
  if bytes >= 1024 then return ("%.1f KB"):format(bytes / 1024) end
  return ("%d B"):format(bytes)
end

-- Plain ASCII throughout. This output is meant to be pasted into a changelog
-- or a README table, and a stray encoding is one more thing that can differ
-- between two runs that should be identical.
local function FormatSpread(fraction) return
  ("+/-%.1f%%"):format(fraction * 100) end

local function FormatDelta(fraction) return ("%+.1f%%"):format(fraction * 100) end

local jit_is_on = false

local function Interpreter()
  if type(jit) == "table" and jit.version then
    local status = {jit.status()}
    jit_is_on = status[1] and true or false
    local flags = {}
    for index = 2, #status do flags[#flags + 1] = tostring(status[index]) end
    local detail = ""
    if #flags > 0 then detail = " (" .. table.concat(flags, " ") .. ")" end
    return ("%s, jit.status() %s%s"):format(jit.version,
                                            status[1] and "on" or "off", detail)
  end
  return _VERSION
end

-- A number without the interpreter it was taken on is not a measurement.
io.write("\n")
io.write("# interpreter  ", Interpreter(), "\n")
io.write("# module       ", guard_api.label, "\n")
if reference_api then
  io.write("# reference    ", reference_api.label, " from ", reference_path,
           "\n")
else
  io.write("# reference    none; absolute numbers only\n")
end
io.write(("# seed         %d\n"):format(seed))
io.write(("# rounds       %d alternated\n"):format(rounds))
io.write(
  ("# corpus       %d B of text -> %d B member, %d B stored member,\n"):format(
    TEXT_BYTES, #text_member, #stored_member))
io.write(("#              %d B small message -> %d B encoded\n"):format(
           SMALL_BYTES, #small_encoded))
io.write(("# cross-checks %d passed\n"):format(checks_run))

-- Measured, not assumed. With the JIT on, a delta on this workload moves by
-- more between two runs of this file than the within-run spread it reports:
-- the two modules are near-identical 4000-line copies sharing one trace
-- cache, and which traces survive a run is not the same twice. With -joff the
-- same shapes repeat to a point or two. That is also the interpreter proxy
-- every number this repository has published was taken on, so it is the same
-- recommendation twice over rather than a preference.
if jit_is_on then
  io.write("#\n")
  io.write(
    "# NOTE  The JIT is on. Run this with \"luajit -joff\" for anything\n")
  io.write("#       that goes into a document: the spread below describes one\n")
  io.write("#       run, and with the JIT on a delta can move further than it\n")
  io.write("#       between runs. -joff is also the World of Warcraft\n")
  io.write("#       interpreter proxy the rest of this repository quotes.\n")
end

-- The six migration-relevant paths.
io.write("\n## Migration paths, \"addon\" policy on this module\n\n")
local floor_notes = {}
if reference_api then
  io.write(("%-38s %6s %10s %10s %9s %8s\n"):format("Path", "calls", "this us",
                                                    "ref us", "delta", "spread"))
  io.write(string.rep("-", 86), "\n")
  local alloc_rows = {}
  for _, shape in ipairs(migration_shapes) do
    local measured = Measure(shape, {guard_api, reference_api})
    local mine, theirs, ratio = measured[1], measured[2], measured.ratio
    local delta = ratio.median - 1
    io.write(("%-38s %6d %10.2f %10.2f %9s %8s\n"):format(shape.name,
                                                          measured.calls,
                                                          mine.median * 1e6,
                                                          theirs.median * 1e6,
                                                          FormatDelta(delta),
                                                          FormatSpread(
                                                            ratio.spread)))
    -- Said in words, not left for the reader to work out from two columns.
    if math.abs(delta) <= ratio.spread then
      floor_notes[#floor_notes + 1] =
        ("%s: %s is inside the %s spread of the comparison, report it as about flat"):format(
          shape.name, FormatDelta(delta), FormatSpread(ratio.spread))
    end
    alloc_rows[#alloc_rows + 1] = {
      name = shape.name,
      mine = mine.alloc,
      theirs = theirs.alloc,
      delta = theirs.alloc > 0 and (mine.alloc / theirs.alloc - 1) or 0
    }
  end

  io.write("\n## Allocation per call\n\n")
  io.write(
    ("%-38s %14s %14s %8s\n"):format("Path", "this", "reference", "delta"))
  io.write(("%s\n"):format(string.rep("-", 78)))
  for _, row in ipairs(alloc_rows) do
    io.write(("%-38s %14s %14s %8s\n"):format(row.name, FormatBytes(row.mine),
                                              FormatBytes(row.theirs),
                                              FormatDelta(row.delta)))
  end
else
  io.write(("%-38s %6s %10s %8s %14s\n"):format("Path", "calls", "us/call",
                                                "spread", "alloc/call"))
  io.write(("%s\n"):format(string.rep("-", 80)))
  for _, shape in ipairs(migration_shapes) do
    local measured = Measure(shape, {guard_api})
    local mine = measured[1]
    io.write(("%-38s %6d %10.2f %8s %14s\n"):format(shape.name, measured.calls,
                                                    mine.median * 1e6,
                                                    FormatSpread(mine.spread),
                                                    FormatBytes(mine.alloc)))
  end
end

for _, note in ipairs(floor_notes) do io.write("# ", note, "\n") end

-- The worst work each preset accepts, which is what sizes a policy. Run
-- against this module only: a reference module has no policy to saturate.
io.write("\n## Saturation, worst accepted work per preset\n\n")
io.write(("%-10s %-12s %10s %10s %10s %8s %12s\n"):format("preset", "shape",
                                                          "input", "decoded",
                                                          "ms/call", "spread",
                                                          "alloc/call"))
io.write(("%s\n"):format(string.rep("-", 78)))
for _, shape in ipairs(saturation_shapes) do
  local measured = Measure(shape, {shape.api})
  local mine = measured[1]
  io.write(("%-10s %-12s %10s %10s %10.1f %8s %12s\n"):format(shape.preset,
                                                              shape.shape,
                                                              FormatBytes(
                                                                #shape.input),
                                                              FormatBytes(
                                                                shape.decoded_bytes),
                                                              mine.median * 1e3,
                                                              FormatSpread(
                                                                mine.spread),
                                                              FormatBytes(
                                                                mine.alloc)))
end

io.write("\n")
io.write("# spread is half the p10-p90 band, as a fraction of the median.\n")
io.write("#   Where a reference is compared it is the spread of the paired\n")
io.write("#   per-round ratio, which cancels load common to both modules;\n")
io.write("#   elsewhere it is the spread of the round times themselves, which\n")
io.write("#   is what an absolute number is reproducible to on this machine.\n")
io.write("#   A delta smaller than its spread is the floor talking, not the\n")
io.write("#   code, and is called out above by name.\n")
io.write("# alloc is bytes allocated per call with the collector stopped,\n")
io.write("#   which counts garbage as well as what the call retains. It is\n")
io.write("#   not peak heap; peak heap cannot be sampled from inside Lua.\n")
io.write("# No timing result fails this harness. Only the cross-checks can.\n")
